import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../style/globals.css";

const quicksand = Quicksand({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}`}>{children}</body>
    </html>
  );
}
