import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../style/globals.css";
import StatusMenuContextComponent from "@/context/contextSidebar/StatusMenu";
import { HeaderPage } from "@/components/header/Header";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StatusMenuContextComponent>
        {/* <HeaderPage /> */}
        <body className={`${quicksand.className}`}>{children}</body>
      </StatusMenuContextComponent>
    </html>
  );
}
